version: '3.8'
services:
  agileworks-mcp:
    build:
      context: .
      args:
        BUILD_DATE: ${BUILD_DATE:-unknown}
        VERSION: v0.3.0
        MCP_PORT: ${MCP_PORT:-8002}
        IS_CLOUD: ${IS_CLOUD:-false}
    image: agileworks-mcp:v0.3.0
    container_name: agileworks_mcp
    # .envを用意する場合は以下の設定が必要
    # 反対に.envを用意しない場合はenv_fileを削除すること
    # env_file:
    #   - .env
    ports:
      - "${MCP_PORT:-8002}:${MCP_PORT:-8002}"
    restart: always
